# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba5b1c2a9d462317adac0b93f4bea78612126af499cb903afc2a8719c84d01572f79d76db1624bf13ec821c8fb93c41b666618ea200faecc623548ba5a3807ad

test:
  secret_key_base: f81b13b5e2ed3719c854417caf2e7b63aa76194d8c4afc72ca4b3268fa55a8655d156d654c149df02b13da7ef4d9ce3f6ddd720c4778e1c8a7b1bcd8bdff77b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
